version: 1.2
workflows:
  - subclass: WDL
    name: hello
    topic: Test WDL workflow for Terra
    primaryDescriptorPath: /hello.wdl
    readMePath: /README.md
    authors:
      - orcid: 0000-0001-5213-3401
